### ISSUE TITLE
minibatch k means?

### ISSUE THREAD

**Issue by mhamilton723** [DeMoriarty/fast_pytorch_kmeans#2]
Is it possible to modify the existing implementation to support minibatch k means? Thanks

**Comment by DeMoriarty** [comment]
Hi, the current implementation already supports a limited version of minibatch kmeans, however you need to provide the full training data to the fit / fit_predict method, and fit_predict will randomly select a minibatch from the training data at each iteration of kmeans algorithm. In order to enable it, you should set minibatch parameter to the desired minibatch size, [as shown here](https://github.com/DeMoriarty/fast_pytorch_kmeans/blob/master/fast_pytorch_kmeans/kmeans.py#L26-L28) 

If you can't provide full training data all at once, then yes it's possible to modify the current version to support that kind of minibatch kmeans as well.

**Comment by DeMoriarty** [comment]
if you want to run KMeans on GPU, you can take a look at [TorchPQ](https://github.com/DeMoriarty/TorchPQ), there are very fast and memory efficient implementations of KMeans and MinibatchKMeans algorithms. 

[Here is an example of how to use MinibatchKMeans](https://github.com/DeMoriarty/TorchPQ/blob/main/torchpq/kmeans/MinibatchKMeans.py#L34-L43).

**Comment by mhamilton723** [comment]
Thank you for this pointer @DeMoriarty !
